_wandb:
    value:
        cli_version: 0.22.3
        e:
            7h9lsmxi3as76plcinzgg12vgx983nji:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "23622320128"
                codePath: rl/medical_rl.py
                codePathLocal: rl/medical_rl.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "325007450112"
                email: jadeyutseng@gmail.com
                executable: /opt/homebrew/Caskroom/miniforge/base/bin/python
                git:
                    commit: 0707634557d50c3feda97d6ad2501229c06faf0a
                    remote: https://github.com/jade-tseng/agi-house-111.git
                host: Mac.localdomain
                memory:
                    total: "25769803776"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/jade/agi-house-111/rl/medical_rl.py
                python: CPython 3.12.11
                root: /Users/jade/agi-house-111
                startedAt: "2025-11-01T23:13:21.165826Z"
                writerId: 7h9lsmxi3as76plcinzgg12vgx983nji
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 95
            "2":
                - 95
            "3":
                - 13
                - 16
            "4": 3.12.11
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
episodes:
    value: 100
learning_rate:
    value: 0.001
model:
    value: gpt-4
reward_threshold:
    value: 0.8
